### ISSUE TITLE
ListUtils ---> Mappers

### ISSUE THREAD

**Issue by SeymurMammadrza** [ColdTea-Projects/verborum_ms#6]
https://github.com/ColdTea-Projects/verborum_ms/blob/024d292409436d6a74210402a0efcd73d1222f33/ms_dictionary/src/main/java/de/coldtea/verborum/msdictionary/common/utils/ListUtils.java#L11

Bu belki scalada olsa, güzel bir hamle derdim. Ama springbootda bu tarz işler için direk Mapstruct ve bilimum tarz mapper library ler var. Baya geniş kullanılıyor. Muhtemelen, bunu iptal etmemizi önereceğim. Pair programmingde birini ben yazarım hatta istersen direk uygulamalı.

@Mapper(componentModel = "spring")
public interface ActEntityMapper {

    @Mapping(target = "actDt", expression =
            "java(az.abb.ms.card.delivery.util.DateTimeUtil.stringToLocalDateTime(dto.getActDt(), \"actDt\"))")
    ActEntity toActEntity(CreateActRequestDto dto);

    CreateActResponseDto toCreateActResponseDto(ActEntity entity);

    ActDto toActDto(ActEntity actEntity);
}

Mapstruct mapper ve bu attığımı araştırmanı öneririm. (c) Sonra functional interface olarak stream icinde filan kullanabiliyoruz, çok tatlı birşey

**Comment by ColdTea-Projects** [comment]
https://media.tenor.com/OtpxOi9YPRcAAAAM/cok-tatlisin-recep-tayyip-erdogan.gif

**Comment by ColdTea-Projects** [comment]
hallederiz 👍
